// fixtures.def.mjs
//
// Synthetic, self-contained regression cases. Navdata is NOT shipped with the
// app (users load their own sector files), so these fixtures fabricate the
// minimum waypoints / STARs / pool needed to drive every parity-critical branch
// of the generation pipeline. Each case is pure data + a fixed RNG seed; the
// golden .scn is whatever the ORACLE (original rc3 code) produces for it, and
// the ported modules must reproduce it byte-for-byte under the same seed.

// Defaults mirror emptyRule() in the rc3 shell so generateFromRule sees a fully
// shaped rule object regardless of which fields a case overrides.
const RULE_DEFAULTS = {
  mode: "S3",
  isDeparture: false,
  poolSource: false,
  poolDep: "",
  poolArr: "",
  spawnWaypoint: "",
  preEntryNm: 10,
  rwyInUse: "",
  fpRouteTemplate: "",
  fpRouteTemplates: [],
  simRouteTemplate: "",
  rate: 8,
  duration: 30,
  startOffset: 0,
  runway: "",
  originPool: "EHAM,EGLL,EDDF,LEMD,LIRF",
  destPool: "LFPG",
  typePool: "A320,A321,B738,A20N,E190",
  typeCategories: [],
  callsignPattern: "AFR###",
  randomCallsign: true,
  heavy: false,
  seq: 1,
  cruiseAlt: 35000,
  spawnAlt: 18000,
  gsMode: "wtc",
  speedType: "ias",
  assignedSpeed: 280,
  squawk: "1000",
  squawkMode: "fixed",
  squawkOptions: ["1000", "2000"],
  reqAltWpt: "",
  reqAltVal: "",
  schedulingMode: "rate",
  nmSeparation: 10,
  excludeNonRouting: true,
};
let _rid = 0;
const rule = (over) => ({ id: `rule-${_rid++}`, name: over.name || "rule", ...RULE_DEFAULTS, ...over });

const WPTS = [
  { name: "RENSA", lat: 49.6, lon: 3.4, type: "FIXES" },
  { name: "VEBEK", lat: 49.3, lon: 3.0, type: "FIXES" },
  { name: "OKABO", lat: 49.05, lon: 2.7, type: "FIXES" },
  { name: "RANUX", lat: 49.85, lon: 3.7, type: "FIXES" },
  { name: "BATAG", lat: 48.6, lon: 2.3, type: "FIXES" },
  { name: "PG270", lat: 49.02, lon: 2.5, type: "FIXES" },
];

const SCEN = () => ({
  name: "LFPG_TEST",
  airportAlt: 0.0,
  ils: [{ name: "27R", lat1: 49.026638, lon1: 2.5617251, lat2: 49.0247256, lon2: 2.5248595 }],
  controllers: [
    { callsign: "LFPG_APP", freq: "126.430" },
    { callsign: "LFPG_TWR", freq: "119.250" },
  ],
  holdings: [],
});

export const CASES = [
  // A — custom-pool arrivals: random callsign, random squawk (incl 56XX),
  // WTC ground speed, preEntryOffset (RENSA upstream of VEBEK), trimRoute, REQALT.
  {
    name: "s3-custom-arrivals",
    seed: 7,
    waypoints: WPTS,
    scenario: SCEN(),
    initPseudoPilot: "PAR_CTR",
    rules: [
      rule({
        name: "VEBEK arrivals",
        isDeparture: false,
        spawnWaypoint: "VEBEK",
        preEntryNm: 10,
        rwyInUse: "27R",
        originPool: "EHAM,EGLL",
        typePool: "A320,B738,A21N",
        fpRouteTemplate: "EHAM DCT RENSA VEBEK OKABO LFPG",
        simRouteTemplate: "RENSA VEBEK OKABO LFPG",
        rate: 6,
        duration: 20,
        spawnAlt: 14000,
        gsMode: "wtc",
        squawkMode: "random",
        squawkOptions: ["1000", "2000", "5600"],
        reqAltWpt: "VEBEK",
        reqAltVal: 7000,
      }),
    ],
  },

  // B — departures, natural speed (gs=0), fixed callsign pattern (expandCS),
  // dest from pool, heading from sim route (PG270 -> BATAG).
  {
    name: "s3-departures-natural",
    seed: 11,
    waypoints: WPTS,
    scenario: SCEN(),
    initPseudoPilot: "",
    rules: [
      rule({
        name: "PG270 departures",
        isDeparture: true,
        randomCallsign: false,
        callsignPattern: "AFR###",
        squawkMode: "fixed",
        squawk: "1000",
        spawnWaypoint: "PG270",
        preEntryNm: 0,
        runway: "27L",
        rwyInUse: "27L",
        destPool: "LFBO,LFML",
        typePool: "A320,A20N",
        fpRouteTemplate: "PG270 BATAG DCT LFBO",
        simRouteTemplate: "PG270 BATAG",
        gsMode: "natural",
        rate: 10,
        duration: 12,
      }),
    ],
  },

  // C — pool source: routeContains filter + excludeNonRouting against STARs,
  // '0000' squawk fallback, per-aircraft FP trim.
  {
    name: "s3-pool-routecontains",
    seed: 23,
    waypoints: WPTS,
    scenario: SCEN(),
    initPseudoPilot: "PAR_CTR",
    stars: [
      {
        airport: "LFPG",
        runway: "27R",
        name: "RENSA1A",
        waypoints: ["RENSA", "VEBEK", "OKABO"],
        iaf: "VEBEK",
      },
    ],
    pool: [
      {
        id: "p1",
        callsign: "KLM44",
        type: "B738",
        origin: "EHAM",
        dest: "LFPG",
        route: "EHAM DCT RENSA VEBEK OKABO LFPG",
        cruiseFL: 350,
        squawk: "2000",
        source: "vatsim",
      },
      {
        id: "p2",
        callsign: "BAW12",
        type: "A320",
        origin: "EGLL",
        dest: "LFPG",
        route: "EGLL DCT RENSA VEBEK LFPG",
        cruiseFL: 360,
        squawk: "0000",
        source: "vatsim",
      },
      {
        id: "p3",
        callsign: "DLH99",
        type: "A21N",
        origin: "EDDF",
        dest: "LFPG",
        route: "EDDF DCT BATAG LFPG",
        cruiseFL: 340,
        squawk: "1000",
        source: "simbrief",
      },
    ],
    rules: [
      rule({
        name: "Pool arrivals via RENSA",
        isDeparture: false,
        poolSource: true,
        poolArr: "LFPG",
        routeContains: "RENSA",
        excludeNonRouting: true,
        spawnWaypoint: "VEBEK",
        rwyInUse: "27R",
        preEntryNm: 5,
        simRouteTemplate: "",
        rate: 8,
        duration: 30,
        spawnAlt: 13000,
        squawkMode: "fixed",
        squawk: "1000",
      }),
    ],
  },

  // D — C1 enroute: Mach->TAS fixed speed, NM-separation scheduling, heavy
  // callsign pool, HJ squawk exclusion of 1000.
  {
    name: "c1-enroute-mach",
    seed: 29,
    waypoints: WPTS,
    scenario: SCEN(),
    initPseudoPilot: "PAR_CTR",
    rules: [
      rule({
        name: "RANUX enroute",
        mode: "C1",
        isDeparture: false,
        heavy: true,
        spawnWaypoint: "RANUX",
        rwyInUse: "27R",
        originPool: "EDDF",
        typePool: "A359,B77W",
        fpRouteTemplate: "RANUX OKABO LFPG",
        simRouteTemplate: "RANUX OKABO",
        gsMode: "fixed",
        speedType: "mach",
        assignedSpeed: 0.78,
        spawnAlt: 35000,
        schedulingMode: "separation",
        nmSeparation: 10,
        squawkMode: "random",
        squawkOptions: ["1000", "2000"],
        preEntryNm: 0,
      }),
    ],
  },

  // E — RNG-free serializer anchor: holdings (L & R), two ILS lines, controllers,
  // a departure (runway-heading fallback), an arrival with preEntryOffset, REQALT,
  // and INITIALPSEUDOPILOT. No rules -> no randomness.
  {
    name: "serializer-manual",
    seed: 1,
    waypoints: WPTS,
    initPseudoPilot: "PAR_CTR",
    scenario: {
      name: "LFPG_MANUAL",
      airportAlt: 392.0,
      ils: [
        { name: "27R", lat1: 49.026638, lon1: 2.5617251, lat2: 49.0247256, lon2: 2.5248595 },
        { name: "26L", lat1: 48.9949188, lon1: 2.6024601, lat2: 48.9929434, lon2: 2.5657057 },
      ],
      controllers: [
        { callsign: "LFPG_APP", freq: "126.430" },
        { callsign: "LFPG_TWR", freq: "119.250" },
      ],
      holdings: [
        { fix: "OKABO", inboundCourse: 270, turn: "L" },
        { fix: "RANUX", inboundCourse: 90, turn: "R" },
      ],
    },
    manualAircraft: [
      {
        callsign: "AFR1234",
        squawk: "2000",
        type: "A320",
        origin: "LFPG",
        dest: "LFBO",
        cruiseAlt: 35000,
        lat: 49.02,
        lon: 2.5,
        alt: 0,
        gs: 0,
        runway: "27L",
        spawnWaypoint: "",
        preEntryNm: 0,
        fpRoute: "PG270 BATAG DCT LFBO",
        simRoute: "PG270 BATAG",
        start: 0,
        reqAltWpt: "",
        reqAltVal: "",
        isDeparture: true,
      },
      {
        callsign: "BAW221",
        squawk: "1000",
        type: "A21N",
        origin: "EGLL",
        dest: "LFPG",
        cruiseAlt: 36000,
        lat: 49.3,
        lon: 3.0,
        alt: 14000,
        gs: 280,
        runway: "27R",
        spawnWaypoint: "VEBEK",
        preEntryNm: 12,
        fpRoute: "EGLL DCT RENSA VEBEK OKABO LFPG",
        simRoute: "RENSA VEBEK OKABO LFPG",
        start: 8,
        reqAltWpt: "VEBEK",
        reqAltVal: 7000,
        isDeparture: false,
      },
    ],
  },

  // F — S1 ground generator (separate plugin): stand assignment + ground aircraft.
  {
    name: "s1-ground-lfbo",
    seed: 5,
    plugin: "reference/scenario-s1-ground.js",
    waypoints: [],
    initPseudoPilot: "",
    scenario: {
      name: "LFBO_GROUND",
      airportAlt: 499.0,
      ils: [],
      controllers: [{ callsign: "LFBO_TWR", freq: "118.100" }],
      holdings: [],
    },
    ground: {
      cfg: {
        mode: "S1",
        airport: "LFBO",
        depRwy: "14R",
        arrRwy: "14L",
        total: 10,
        initialPopulated: 3,
        sessionLen: 30,
        vfrCount: 2,
        depRatio: 0.7,
        minArrSpacing: 3.0,
        twoGateSpacing: false,
      },
      gates: [],
      rampAgent: {},
    },
  },
];
